// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dohxjlmmwhiueujmjxnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvaHhqbG1td2hpdWV1am1qeG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNDQ0NTAsImV4cCI6MjA1NTgyMDQ1MH0.mTcB_iBKeH-enO6JGudPnPAgKBCJM-1YjzAcDy3Z-H8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);